import Footer from '@/components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] })

export const metadata = {
  title: 'Google Clone',
  description: 'Generated by create next app',
  icons:{
    icon: './favicon.svg'
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative min-h-screen`}>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
