
import { Inter } from 'next/font/google'
import { Poppins } from 'next/font/google'
import SearchHeader from '@/components/SearchHeader'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] })

export const metadata = {
  title: 'Google Clone',
  description: 'Generated by create next app',
  icons:{
    icon: './favicon.svg'
  }
}

export default function SearchLayout({ children }) {
  return (
    
      <div className={poppins.className}>
        <SearchHeader/>
        {children}
        </div>
   
  )
}
